### ISSUE TITLE
Y'allses isn't necessarily a word used in the English language

### ISSUE THREAD

**Issue by Furaux** [Ovinr/hitlang-makhi#1]
If it is possessive, then I will personally hit you with a Bloody a-70x and get good hitreg.

**Comment by Ovinr** [comment]
Thank you for reporting this bug, our team will work as quickly as possible to resolve it.
Keep in mind, however we have a lot of work to do so the bug may be fixed in a later patch
-Ta, Seth Voelker

**Comment by Furaux** [comment]
ur so cool!! its nice to see a developer listening to their userbase.

**Comment by Ovinr** [comment]
thanks! <3

**Comment by Ovinr** [comment]
Test
